/// Named route paths for the Alter UI shell.
abstract final class AlterRoutes {
  static const ftueWhat = '/';
  static const features = '/features';
  static const getStarted = '/get-started';
  static const login = '/login';
  static const permissions = '/permissions';
  static const languages = '/languages';
  static const about = '/about';
  static const home = '/home';
  static const backend = '/backend';
  static const settings = '/settings';
  static const profile = '/profile';
  static const voice = '/voice';
  static const feed = '/feed';
  static const contextos = '/contextos';
  static const twin = '/twin';
  static const shield = '/shield';
  static const dayTwin = '/daytwin';
  static const futureTwin = '/futuretwin';
  static const decisionCouncil = '/decision-council';
  static const decisionDna = '/dna';
  static const memory = '/memory';
  static const edge = '/edge';
  static const mission = '/mission';
  static const officeKit = '/officekit';
  static const privacy = '/privacy';
  static const reputation = '/reputation';
  static const council = '/council';
  static const simulator = '/simulator';
  static const radar = '/radar';
  static const social = '/social';
  static const deepAnalysis = '/deep-analysis';
  static const lens = '/lens';
  static const nfc = '/nfc';
  static const openclaw = '/openclaw';
  static const agent = '/agent';
}
